#!/usr/bin/env perl

use strict;
use warnings;

my $change = shift;

if ($change) {
  chomp( my $current = `xbacklight` );
  my $step = $current <= 7 ? 1 : 5; 
  if ($change eq "up") {
    system `xbacklight -time 250 +$step`;
  }
  elsif ($change eq "down") {
    system `xbacklight -time 250 -$step`;
  }
}

my $brightness = int(qx{xbacklight});

exec "notify-send", " ",
      "-i", "notification-display-brightness-low",
      "-h", "int:value:$brightness",
      "-h", "string:x-canonical-private-synchronous:brightness";
