#!/bin/bash

i3-msg "exec urxvtcd; exec irc; exec urxvtcd"
i3-msg "workspace 1; append_layout $HOME/.i3/workspace-1.json"

i3-msg "exec chromium; exec 1password; exec outlook"
i3-msg "workspace 2; append_layout $HOME/.i3/workspace-2.json"
