#!/bin/bash

file="$(date +%Y%m%d%H%M%s)-screenshot.png"
path="$HOME/screenshots/$file"
scrot -b -s $path
echo -n "http://prettybrd.com/~leedo/b/screenshots/$file" | xclip -i -selection clipboard
echo -n "http://prettybrd.com/~leedo/b/screenshots/$file" | xclip -i
scp $path kvothe:~/p/b/screenshots/
